import 'package:flutter/material.dart';

class Book {
  final String title;
  final String author;
  final String image;
  final String description;
  final double price;
  final String category;
  bool isFavorite;

  Book({
    required this.title,
    required this.author,
    required this.image,
    required this.description,
    required this.price,
    required this.category,
    this.isFavorite = false,
  });
}

List<Book> bookList = [
  Book(
    title: 'Castle in the Sky',
    author: 'Hayao Miyazaki',
    image: 'images/01.png',
    description: 'Art and concept sketches from the film Castle in the Sky.',
    price: 24.99,
    category: 'Art',
  ),
  Book(
    title: '50 Simple Things You Can Do to Save the Earth',
    author: 'The EarthWorks Group',
    image: 'images/02.png',
    description: 'A practical guide with actionable steps for environmental conservation.',
    price: 18.99,
    category: 'Environment',
  ),
  Book(
    title: 'Flovely and Unicorn Erna',
    author: 'Sieber Steffen',
    image: 'images/03.png',
    description: 'A lovely children’s story about friendship and imagination.',
    price: 9.99,
    category: 'Children',
  ),
  Book(
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    image: 'images/04.png',
    description: 'A philosophical tale about a shepherd’s journey to find his personal legend.',
    price: 14.99,
    category: 'Fiction',
  ),
  Book(
    title: 'Apple iPod with Retina Display',
    author: 'Harper Lee',
    image: 'images/05.png',
    description: "Explores Apple's Retina Display technology introduced in 2010 and its visual clarity.",
    price: 22.99,
    category: 'Technology',
  ),
  Book(
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    image: 'images/06.jpeg',
    description: 'A hobbit’s unexpected adventure.',
    price: 18.99,
    category: 'Fantasy',
  ),
  Book(
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    image: 'images/07.jpeg',
    description: 'What the rich teach their kids about money.',
    price: 21.50,
    category: 'Finance',
  ),
  Book(
    title: 'Atomic Habits',
    author: 'James Clear',
    image: 'images/08.jpeg',
    description: 'Tiny changes make a big difference.',
    price: 19.99,
    category: 'Self-Help',
  ),
  Book(
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    image: 'images/09.jpeg',
    description: 'A deep look into racial injustice and childhood.',
    price: 16.75,
    category: 'Classic',
  ),
  Book(
    title: 'Deep Work',
    author: 'Cal Newport',
    image: 'images/10.jpg',
    description: 'Rules for focused success in a distracted world.',
    price: 17.99,
    category: 'Productivity',
  ),
  Book(
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    image: 'images/11.jpeg',
    description: 'Timeless lessons on wealth and behavior.',
    price: 17.99,
    category: 'Finance',
  ),
  Book(
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    image: 'images/12.jpeg',
    description: 'Living in the present moment.',
    price: 17.99,
    category: 'Spirituality',
  ),
  Book(
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    image: 'images/13.jpeg',
    description: 'A brief history of humankind.',
    price: 17.99,
    category: 'History',
  ),
  Book(
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    image: 'images/14.jpeg',
    description: 'Classic strategies for success.',
    price: 17.99,
    category: 'Motivation',
  ),
  Book(
    title: 'Life of Pi',
    author: 'Yann Martel',
    image: 'images/15.jpg',
    description: 'An epic journey of survival and spirituality on the open sea.',
    price: 17.25,
    category: 'Motivation',
  ),
  Book(
    title: "King Solomon's Mines",
    author: 'H. Rider Haggard',
    image: 'images/16.jpeg',
    description: 'A thrilling African adventure with ancient treasure and danger.',
    price: 15.00,
    category: 'Motivation',
  ),
  Book(
    title: 'The Adventures of Huckleberry Finn',
    author: 'Mark Twain',
    image: 'images/17.jpeg',
    description: 'A young boy’s journey down the Mississippi River with a runaway slave.',
    price: 13.75,
    category: 'Motivation',
  ),
  Book(
    title: "The Call of the Wild",
    author: 'Jack London',
    image: 'images/18.jpg',
    description: 'Follow Buck, a domestic dog thrust into the harsh life of the Alaskan wilderness, in this gripping story of survival and instinct.',
    price: 12.50,
    category: 'Adventure',
  ),

  Book(
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    image: 'images/19.jpeg',
    description: 'An epic tale of pirates, buried treasure, and high seas adventure. Join young Jim Hawkins on a dangerous journey full of twists and betrayals.',
    price: 17.99,
    category: 'Adventure',
  ),
  Book(
    title: 'Foundation',
    author: 'Isaac Asimov',
    image: 'images/20.jpg',
    description: 'A visionary psychohistorian predicts the fall of the galactic empire and secretly sets out to preserve knowledge for the future.',
    price: 15.00,
    category: 'Science Fiction',
  ),
  Book(
    title: "Ender's Game",
    author: 'Orson Scott Card',
    image: 'images/21.jpg',
    description: 'A gifted boy is trained through intense war games to save humanity from an alien threat. Smart, strategic, and emotional.',
    price: 14.25,
    category: 'Science Fiction',
  ),
  Book(
    title: "Neuromancer",
    author: 'William Gibson',
    image: 'images/22.jpg',
    description: 'A washed-up hacker is hired for one last job in a world of AI, cybernetics, and a digital matrix that predicted the internet.',
    price: 13.50,
    category: 'Cyberpunk',
  ),
  Book(
    title: 'Dune',
    author: 'Frank Herbert',
    image: 'images/23.jpg',
    description: 'In a distant future where spice controls the universe, Paul Atreides must survive political betrayal and fulfill a great destiny.',
    price: 17.99,
    category: 'Science Fiction',
  ),
  Book(
    title: 'Simple Things You Can Do to Save the Earth',
    author: 'The EarthWorks Group',
    image: 'images/24.jpg',
    description: 'A practical guide with actionable steps for environmental conservation and grassroots movements.',
    price: 29.99,
    category: 'Environment',
  ),
  Book(
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    image: 'images/25.jpeg',
    description: 'A brutally honest and humorous look at how to focus on what really matters in life.',
    price: 14.50,
    category: 'Self-Help',
  ),
  Book(
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    image: 'images/26.jpg',
    description: "A classic blueprint for success based on insights from the world's most successful individuals.",
    price: 13.99,
    category: 'Motivation',
  ),
  Book(
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    image: 'images/27.jpeg',
    description: 'A timeless guide to personal and professional effectiveness, grounded in values and proactive principles.',
    price: 15.99,
    category: 'Self-Help',
  ),
  Book(
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    image: 'images/28.jpg',
    description: "A man wakes up alone in space with no memory—and must save Earth from extinction. Brilliantly inventive and heartfelt.",
    price: 16.99,
    category: 'Science Fiction',
  ),
  Book(
    title: 'The Martian',
    author: 'Andy Weir',
    image: 'images/29.jpg',
    description: 'Stranded alone on Mars, astronaut Mark Watney must survive using science, wit, and sheer willpower.',
    price: 14.75,
    category: 'Science Fiction',
  ),
];
